// AIDI Pipeline Dashboard v6
// Reads data.json generated by snapshot.ts

const REFRESH = 60000;
let DATA = null;
let groupSort = 'future'; // 'future' | 'name' | 'city' | 'test' | 'pending'

async function load() {
  try {
    const r = await fetch('data.json?t=' + Date.now());
    DATA = await r.json();
    render();
  } catch (e) { console.error('fetch failed:', e); }
}

function render() {
  if (!DATA) return;
  renderHeader();
  renderFunnel();
  renderAlerts();
  renderGroupTiers();
  renderGroupTable();
  renderScatter();
  renderStateBars();
  renderRegions();
  renderPorter();
  renderTimeline();
  renderVenuesOrgs();
  renderHarvey();
  renderHealth();
}

// ═══ HEADER ═══

function renderHeader() {
  const ts = new Date(DATA.generated_at);
  const ageSec = Math.round((Date.now() - ts.getTime()) / 1000);
  const age = ageSec < 60 ? ageSec + 's' : ageSec < 3600 ? Math.round(ageSec/60) + 'm' : Math.round(ageSec/3600) + 'h';
  document.getElementById('last-updated').textContent = `Data: ${age} ago`;

  const badge = document.getElementById('health-badge');
  badge.textContent = DATA.health;
  badge.className = 'health-badge ' + DATA.health.toLowerCase();

  const dbEl = document.getElementById('db-status');
  const chrome = DATA.scraper?.chrome === 'UP';
  const booker = DATA.booker !== null;
  dbEl.innerHTML = `Booker: <span class="${booker ? 'connected' : 'disconnected'}">${booker ? 'ok' : 'offline'}</span> &nbsp; Chrome: <span class="${chrome ? 'connected' : 'disconnected'}">${chrome ? 'UP :9223' : 'DOWN'}</span>`;
}

// ═══ FUNNEL ═══

function renderFunnel() {
  const f = DATA.booker?.funnel;
  const gf = DATA.booker?.groupFreshness;
  if (!f) return;

  document.getElementById('f-groups').textContent = gf?.total || '--';
  document.getElementById('f-groups-sub').textContent = `${gf?.fresh_1d || 0} scraped today`;
  document.getElementById('f-discovered').textContent = f.total_discovered;
  document.getElementById('f-discovered-sub').textContent = `all time`;
  document.getElementById('f-future').textContent = f.future;
  document.getElementById('f-future-sub').textContent = `${f.future_with_venue} have venue`;
  document.getElementById('f-ready').textContent = f.ready_for_porter;
  document.getElementById('f-ready-sub').textContent = `with venue, not loaded`;
  document.getElementById('f-prod').textContent = f.in_prod;

  // Drops
  document.getElementById('f-drop-class').textContent = `${f.skipped_class} class-only (by design)`;
  document.getElementById('f-drop-venue').textContent = `${f.missing_venue} missing venue`;
  document.getElementById('f-drop-skipped').textContent = `${f.skipped_other} skipped (dupe/other)`;
  document.getElementById('f-drop-past').textContent = `${f.past} past events`;
}

// ═══ ALERTS ═══

function renderAlerts() {
  const el = document.getElementById('alerts-bar');
  const icons = { critical: '\uD83D\uDD34', warning: '\uD83D\uDFE1', info: '\uD83D\uDD35', ok: '\uD83D\uDFE2' };
  const alerts = DATA.alerts || [];
  if (alerts.length === 0) {
    el.innerHTML = '<div class="alert-item ok">All systems nominal</div>';
    return;
  }
  el.innerHTML = alerts.map(a =>
    `<div class="alert-item ${a.level}">${icons[a.level] || ''} [${a.source}] ${a.message}</div>`
  ).join('');
}

// ═══ GROUP TIERS ═══

function renderGroupTiers() {
  const tiers = DATA.booker?.groupTiers || [];
  const gf = DATA.booker?.groupFreshness || {};

  document.getElementById('group-total').textContent = gf.total || '--';

  const tierColors = { high: 'c-ok', normal: 'c-blue', dormant: 'c-muted' };
  document.getElementById('group-tiers').innerHTML = tiers.map(t => {
    const cls = tierColors[t.tier] || 'c-muted';
    return `<div class="tier-card">
      <div class="tier-name">${t.tier}</div>
      <div class="tier-total ${cls}">${t.total}</div>
      <div class="tier-detail">${t.proven} proven / ${t.untested} untested</div>
    </div>`;
  }).join('');

  document.getElementById('group-freshness').innerHTML = `
    <div class="freshness-item"><div class="f-val c-ok">${gf.fresh_1d || 0}</div><div class="f-label">Today</div></div>
    <div class="freshness-item"><div class="f-val c-ok">${gf.fresh_7d || 0}</div><div class="f-label">&lt;7 days</div></div>
    <div class="freshness-item"><div class="f-val c-warn">${gf.stale || 0}</div><div class="f-label">Stale</div></div>
    <div class="freshness-item"><div class="f-val c-muted">${gf.never_scraped || 0}</div><div class="f-label">Never</div></div>
  `;
}

// ═══ GROUP TABLE ═══

function renderGroupTable() {
  const groups = DATA.booker?.groups || [];
  const sorted = [...groups].sort((a, b) => {
    if (groupSort === 'future') return (b.future_events || 0) - (a.future_events || 0);
    if (groupSort === 'name') return a.name.localeCompare(b.name);
    if (groupSort === 'city') return (a.city || '').localeCompare(b.city || '');
    if (groupSort === 'test') return (b.test_synced || 0) - (a.test_synced || 0);
    if (groupSort === 'pending') return (b.pending || 0) - (a.pending || 0);
    return 0;
  });

  document.getElementById('group-table').innerHTML = sorted.map(g => {
    const age = formatAge(g.last_scraped_at);
    const ageCls = age === 'never' ? 'c-bad' : age.includes('d') && parseInt(age) > 7 ? 'c-warn' : 'c-ok';
    return `<div class="group-table-row" data-group-id="${g.id}">
      <span class="col-name" title="${g.name}">${g.name}</span>
      <span class="col-city">${g.city || '--'}${g.state ? ', ' + g.state : ''}</span>
      <span class="col-tier"><span class="tier-badge ${g.tier}">${g.tier}</span></span>
      <span class="col-num c-muted">${g.total_events || 0}</span>
      <span class="col-num c-blue">${g.future_events || 0}</span>
      <span class="col-num ${g.prod_synced ? 'c-ok' : 'c-muted'}">${g.prod_synced || 0}</span>
      <span class="col-num ${g.pending > 0 ? 'c-purple' : 'c-muted'}">${g.pending || 0}</span>
      <span class="col-num"></span>
      <span class="col-age ${ageCls}">${age}</span>
    </div>`;
  }).join('');

  // Click handlers
  document.querySelectorAll('#group-table .group-table-row').forEach(row => {
    row.addEventListener('click', () => {
      const id = parseInt(row.getAttribute('data-group-id'));
      openGroupDrawer(id);
    });
  });
}

// ═══ GROUP DRAWER (click detail) ═══

function openGroupDrawer(groupId) {
  const group = DATA.booker?.groups?.find(g => g.id === groupId);
  if (!group) return;

  document.getElementById('drawer-title').textContent = group.name;

  // Find events for this group from regions/statuses (approximate — we show group-level stats)
  const content = document.getElementById('drawer-content');
  const age = formatAge(group.last_scraped_at);

  content.innerHTML = `
    <div class="drawer-stats">
      <div class="metric-card"><div class="value c-muted">${group.total_events || 0}</div><div class="label">Total Events</div></div>
      <div class="metric-card"><div class="value c-blue">${group.future_events || 0}</div><div class="label">Future</div></div>
      <div class="metric-card"><div class="value c-warn">${group.test_synced || 0}</div><div class="label">In TEST</div></div>
      <div class="metric-card"><div class="value c-ok">${group.prod_synced || 0}</div><div class="label">In PROD</div></div>
      <div class="metric-card"><div class="value c-purple">${group.pending || 0}</div><div class="label">Pending</div></div>
    </div>
    <div style="display:flex; gap:1rem; flex-wrap:wrap; font-size:0.8rem; color:#aaa; margin-bottom:0.5rem;">
      <span><strong>City:</strong> ${group.city || '--'}${group.state ? ', ' + group.state : ''}</span>
      <span><strong>Tier:</strong> <span class="tier-badge ${group.tier}">${group.tier}</span></span>
      <span><strong>Type:</strong> ${group.group_type || 'unknown'}</span>
      <span><strong>Last scraped:</strong> <span class="${age === 'never' ? 'c-bad' : 'c-ok'}">${age}</span></span>
      <span><strong>Empty runs:</strong> ${group.consecutive_empty_scrapes || 0}</span>
    </div>
    ${group.url ? `<a href="${group.url}" target="_blank" style="color:#3b82f6; font-size:0.75rem;">Open FB Group &rarr;</a>` : ''}
  `;

  document.getElementById('group-drawer').classList.remove('hidden');
}

document.getElementById('drawer-close')?.addEventListener('click', () => {
  document.getElementById('group-drawer').classList.add('hidden');
});

// Sort toggle
document.getElementById('group-sort-toggle')?.addEventListener('click', () => {
  const order = ['future', 'pending', 'test', 'city', 'name'];
  groupSort = order[(order.indexOf(groupSort) + 1) % order.length];
  document.getElementById('group-sort-toggle').textContent = 'sort: ' + groupSort;
  renderGroupTable();
});

// ═══ REGIONS ═══

function renderRegions() {
  const regions = DATA.booker?.regions || [];
  document.getElementById('region-table').innerHTML = regions.slice(0, 30).map(r => `
    <div class="region-table-row">
      <span class="col-name">${r.city}${r.state ? ', ' + r.state : ''}</span>
      <span class="col-num c-blue">${r.events}</span>
      <span class="col-num ${r.prod_synced ? 'c-ok' : 'c-muted'}">${r.prod_synced || 0}</span>
      <span class="col-num c-muted">${r.venues || 0}</span>
      <span class="col-num"></span>
    </div>
  `).join('');
}

// ═══ PORTER ═══

function renderPorter() {
  const ps = DATA.booker?.porterSync;
  if (!ps) return;

  document.getElementById('porter-sync').innerHTML = `
    <div class="metric-card"><div class="value c-ok">${ps.prod_synced || 0}</div><div class="label">In PROD</div></div>
    <div class="metric-card"><div class="value c-purple">${ps.pending || 0}</div><div class="label">Ready to Load</div></div>
    <div class="metric-card"><div class="value c-bad">${ps.blocked_no_venue || 0}</div><div class="label">No Venue</div></div>
    <div class="metric-card"><div class="value c-muted">${ps.skip_class || 0}</div><div class="label">Class (skip)</div></div>
    <div class="metric-card"><div class="value c-muted">${ps.skipped || 0}</div><div class="label">Skipped</div></div>
  `;

  // History bars
  const hist = DATA.booker?.porterHistory || [];
  if (hist.length === 0) {
    document.getElementById('porter-history').innerHTML = '<div style="color:#555; text-align:center; padding:0.5rem;">No load history</div>';
    return;
  }
  const max = Math.max(...hist.map(h => (h.loaded_test || 0) + (h.loaded_prod || 0)), 1);
  document.getElementById('porter-history').innerHTML =
    hist.slice(0, 10).reverse().map(h => {
      const testW = ((h.loaded_test || 0) / max) * 100;
      const prodW = ((h.loaded_prod || 0) / max) * 100;
      return `<div class="chart-row">
        <span class="chart-label">${h.day?.slice(5) || '--'}</span>
        <div class="chart-bars">
          <div class="chart-bar-test" style="width:${testW}%" title="TEST: ${h.loaded_test}"></div>
          <div class="chart-bar-prod" style="width:${prodW}%" title="PROD: ${h.loaded_prod}"></div>
        </div>
        <span class="chart-count">${(h.loaded_test || 0) + (h.loaded_prod || 0)}</span>
      </div>`;
    }).join('') +
    `<div class="chart-legend">
      <span><span class="legend-dot" style="background:#3b82f6"></span> TEST</span>
      <span><span class="legend-dot" style="background:#4ade80"></span> PROD</span>
    </div>`;
}

// ═══ EVENT TIMELINE (discovery rate — future events only) ═══

function renderTimeline() {
  const tl = DATA.booker?.eventTimeline || [];
  if (tl.length === 0) {
    document.getElementById('event-timeline').innerHTML = '<div style="color:#555; text-align:center;">No data</div>';
    return;
  }
  const max = Math.max(...tl.map(t => t.future_added || 0), 1);
  document.getElementById('event-timeline').innerHTML =
    tl.filter(t => (t.future_added || 0) > 0).slice(0, 14).reverse().map(t => {
      const w = ((t.future_added || 0) / max) * 100;
      return `<div class="chart-row">
        <span class="chart-label">${t.day?.slice(5) || '--'}</span>
        <div class="chart-bars">
          <div class="chart-bar-future" style="width:${w}%"></div>
        </div>
        <span class="chart-count">+${t.future_added || 0}</span>
      </div>`;
    }).join('') +
    `<div class="chart-legend">
      <span><span class="legend-dot" style="background:#06b6d4"></span> Future events discovered</span>
    </div>`;
}

// ═══ SCATTER: Events over next 90 days ═══

const SCATTER_COLORS = {
  // By pipeline status
  prod:    '#4ade80',  // green — in PROD
  test:    '#facc15',  // yellow — in TEST
  ready:   '#3b82f6',  // blue — ready for Porter
  pending: '#8b5cf6',  // purple — no venue yet
  skip:    '#666',     // grey — skipped
};

function renderScatter() {
  const events = DATA.booker?.scatter || [];
  const el = document.getElementById('scatter-chart');
  if (!events.length) { el.innerHTML = '<div style="color:#555;text-align:center;padding:2rem;">No future events</div>'; return; }

  // X axis: days from now (0-90)
  // Y axis: states, grouped
  const states = [...new Set(events.map(e => e.state || e.country || '??'))].sort();
  const stateIndex = {};
  states.forEach((s, i) => stateIndex[s] = i);

  const now = Date.now();
  const day90 = 90 * 24 * 60 * 60 * 1000;

  let html = '';

  // Grid lines per week
  for (let w = 0; w <= 12; w++) {
    const x = (w * 7 / 90) * 100;
    html += `<div class="scatter-grid-line" style="left:${x}%; top:0; bottom:0; width:1px; height:100%;"></div>`;
    if (w % 2 === 0) {
      const d = new Date(now + w * 7 * 86400000);
      html += `<div class="scatter-date-label" style="left:${x}%">${(d.getMonth()+1)}/${d.getDate()}</div>`;
    }
  }

  // State labels on Y axis
  const stateH = 100 / Math.max(states.length, 1);
  states.forEach((s, i) => {
    const y = (i + 0.5) * stateH;
    html += `<div class="scatter-state-label" style="top:${y}%">${s}</div>`;
    if (i > 0) html += `<div class="scatter-grid-line" style="top:${i * stateH}%"></div>`;
  });

  // Dots
  for (const e of events) {
    const dt = new Date(e.start_dt).getTime();
    const dayOffset = dt - now;
    if (dayOffset < 0 || dayOffset > day90) continue;

    const x = (dayOffset / day90) * 100;
    const stKey = e.state || e.country || '??';
    const yBase = (stateIndex[stKey] || 0) * stateH;
    const y = yBase + (Math.random() * 0.6 + 0.2) * stateH; // jitter within band

    const color = SCATTER_COLORS[e.pipeline_status] || '#666';
    const venue = e.has_venue ? 'border:1px solid rgba(255,255,255,0.4)' : '';
    const title = `${e.title || 'event'}\n${e.city || ''}${e.state ? ', '+e.state : ''}\n${e.day} | ${e.category}\nStatus: ${e.pipeline_status}${e.has_venue ? ' | has venue' : ' | NO venue'}`;

    html += `<div class="scatter-dot" style="left:${x}%;top:${y}%;background:${color};${venue}" title="${title.replace(/"/g, '&quot;')}"></div>`;
  }

  el.innerHTML = html;

  // Legend
  document.getElementById('scatter-legend').innerHTML = `
    <span><span class="legend-dot" style="background:#4ade80"></span> In PROD</span>
    <span><span class="legend-dot" style="background:#facc15"></span> In TEST</span>
    <span><span class="legend-dot" style="background:#3b82f6"></span> Ready</span>
    <span><span class="legend-dot" style="background:#8b5cf6"></span> Pending</span>
    <span><span class="legend-dot" style="background:#666"></span> Skipped</span>
    <span style="color:#555">| ring = has venue</span>
  `;

  // Gaps: find days with zero events
  const dayBuckets = DATA.booker?.eventsByDay || [];
  const daySet = new Set(dayBuckets.map(d => d.day));
  const gaps = [];
  let gapStart = null;
  for (let d = 0; d < 90; d++) {
    const dt = new Date(now + d * 86400000);
    const key = dt.toISOString().slice(0, 10);
    if (!daySet.has(key)) {
      if (!gapStart) gapStart = key;
    } else {
      if (gapStart) {
        const gapEnd = new Date(now + (d-1) * 86400000).toISOString().slice(0, 10);
        gaps.push(gapStart === gapEnd ? gapStart.slice(5) : `${gapStart.slice(5)} to ${gapEnd.slice(5)}`);
        gapStart = null;
      }
    }
  }
  if (gapStart) gaps.push(`${gapStart.slice(5)} onward`);

  const gapsEl = document.getElementById('scatter-gaps');
  if (gaps.length === 0) {
    gapsEl.innerHTML = '<span class="gap-item" style="color:#4ade80">No gaps in next 90 days</span>';
  } else {
    gapsEl.innerHTML = gaps.slice(0, 8).map(g =>
      `<span class="gap-item has-gap">${g}</span>`
    ).join('') + (gaps.length > 8 ? `<span class="c-muted">+${gaps.length - 8} more</span>` : '');
  }
}

// ═══ STATE BARS ═══

function renderStateBars() {
  const states = DATA.booker?.stateRollup || [];
  if (!states.length) return;

  const max = Math.max(...states.map(s => s.events || 0), 1);

  document.getElementById('state-bars').innerHTML =
    states.slice(0, 15).map(s => {
      const evW = ((s.events || 0) / max) * 100;
      const venW = ((s.unique_venues || 0) / max) * 100;
      return `<div class="state-bar-row">
        <span class="state-label">${s.region}</span>
        <div class="state-bars-container">
          <div class="state-bar-events" style="width:${evW}%" title="Events: ${s.events}"></div>
        </div>
        <span class="state-count c-blue">${s.events}</span>
        <div class="state-bars-container" style="max-width:80px">
          <div class="state-bar-venues" style="width:${(s.unique_venues/Math.max(...states.map(x=>x.unique_venues),1))*100}%"></div>
        </div>
        <span class="state-count c-purple">${s.unique_venues}v</span>
        <span class="state-count c-ok">${s.in_prod}p</span>
      </div>`;
    }).join('') +
    `<div class="chart-legend">
      <span><span class="legend-dot" style="background:#3b82f6"></span> Events</span>
      <span><span class="legend-dot" style="background:#8b5cf6"></span> Venues</span>
      <span style="color:#4ade80">p = in PROD</span>
    </div>`;
}

// ═══ VENUES & ORGS ═══

function renderVenuesOrgs() {
  const v = DATA.booker?.venues || {};
  const o = DATA.booker?.organizers || {};
  document.getElementById('venues-orgs').innerHTML = `
    <div class="metric-card"><div class="value c-muted">${v.total || 0}</div><div class="label">Venues</div></div>
    <div class="metric-card"><div class="value c-ok">${v.geocoded || 0}</div><div class="label">Geocoded</div></div>
    <div class="metric-card"><div class="value ${v.missing_geo > 0 ? 'c-bad' : 'c-ok'}">${v.missing_geo || 0}</div><div class="label">Missing Geo</div></div>
    <div class="metric-card"><div class="value c-muted">${o.total || 0}</div><div class="label">Organizers</div></div>
    <div class="metric-card"><div class="value c-blue">${o.with_fb || 0}</div><div class="label">With FB</div></div>
    <div class="metric-card"><div class="value c-ok">${o.contacted || 0}</div><div class="label">Contacted</div></div>
  `;
}

// ═══ HARVEY ═══

function renderHarvey() {
  const h = DATA.harvey || {};
  const sources = h.sources || [];
  const standalone = h.standalone || [];
  const sum = h.summary || {};

  const totalSources = (sum.gcalSources || 0) + (sum.standaloneSites || 0);
  document.getElementById('harvey-total').textContent = `${totalSources} sources`;

  document.getElementById('harvey-summary').innerHTML = `
    <div class="metric-card"><div class="value c-blue">${sum.gcalSources || 0}</div><div class="label">GCal Orgs</div></div>
    <div class="metric-card"><div class="value c-blue">${sum.totalSubCalendars || 0}</div><div class="label">Sub-Cals</div></div>
    <div class="metric-card"><div class="value c-purple">${sum.standaloneSites || 0}</div><div class="label">Sites</div></div>
    <div class="metric-card"><div class="value c-ok">${sum.fresh_7d || 0}</div><div class="label">Fresh (&lt;7d)</div></div>
    <div class="metric-card"><div class="value c-warn">${sum.stale || 0}</div><div class="label">Stale</div></div>
    <div class="metric-card"><div class="value c-muted">${(sum.totalEvents || 0).toLocaleString()}</div><div class="label">Total Events</div></div>
  `;

  // GCal sources (aggregated by org)
  document.getElementById('harvey-gcal-sources').innerHTML = sources.map(s => {
    const age = s.ageHours !== null ? formatHours(s.ageHours) : 'no data';
    const ageCls = s.ageHours === null ? 'c-bad' : s.ageHours < 24 ? 'c-ok' : s.ageHours < 168 ? 'c-ok' : 'c-warn';
    return `<div class="site-table-row">
      <span class="col-name" title="${s.name}">${s.name}</span>
      <span class="col-type" style="color:#888">${s.city}, ${s.state}</span>
      <span class="col-num c-muted">${s.subCalendars}</span>
      <span class="col-num c-blue">${s.events}</span>
      <span class="col-age ${ageCls}">${age}</span>
    </div>`;
  }).join('');

  // Standalone sites
  document.getElementById('harvey-standalone').innerHTML = standalone.map(s => {
    const age = s.ageHours !== null ? formatHours(s.ageHours) : 'no data';
    const ageCls = s.ageHours === null ? 'c-bad' : s.ageHours < 24 ? 'c-ok' : s.ageHours < 168 ? 'c-ok' : 'c-warn';
    return `<div class="site-table-row">
      <span class="col-name">${s.name}</span>
      <span class="col-type" style="color:#666">${s.type}</span>
      <span class="col-num"></span>
      <span class="col-num c-blue">${s.events}</span>
      <span class="col-age ${ageCls}">${age}</span>
    </div>`;
  }).join('');
}

// ═══ HEALTH ═══

function renderHealth() {
  const s = DATA.scraper || {};
  const chCls = s.chrome === 'UP' ? 'c-ok' : 'c-bad';
  const cp = s.checkpoint;
  const cpText = cp ? `${formatAge(cp.timestamp)} (${cp.group || 'unknown'})` : 'No checkpoint';

  document.getElementById('scraper-health').innerHTML = `
    <div class="health-row">
      <span class="label">Chrome CDP</span>
      <span class="${chCls}">${s.chrome || '--'} :${s.cdpPort || '--'}</span>
    </div>
    <div class="health-row">
      <span class="label">Last Scrape Activity</span>
      <span class="c-muted">${cpText}</span>
    </div>
  `;
}

// ═══ UTILS ═══

function formatAge(isoStr) {
  if (!isoStr) return 'never';
  const ms = Date.now() - new Date(isoStr).getTime();
  const mins = Math.round(ms / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return mins + 'm';
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return hrs + 'h';
  const days = Math.round(hrs / 24);
  return days + 'd';
}

function formatHours(h) {
  if (h < 1) return '<1h';
  if (h < 24) return h + 'h';
  return Math.round(h / 24) + 'd';
}

// ═══ BOOT ═══
load();
setInterval(load, REFRESH);
